name: 🌀 Daily Sync with Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # Chạy mỗi ngày lúc 2h sáng UTC (~9h sáng VN)
  workflow_dispatch:     # Cho phép chạy tay nếu cần

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout your repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 🔧 Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 🔄 Add upstream and fetch
        run: |
          git remote add upstream https://github.com/immortalwrt/immortalwrt.git
          git fetch upstream --no-tags

      - name: 🔀 Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories --no-edit || echo "Nothing to merge"

      - name: 🚀 Push changes to your fork (only master branch)
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Doanduy09/Immortalwrt.git master
